app:
  name: "authly"

server:
  host: "0.0.0.0"
  port: 8000

database:
  host: "localhost"
  port: 5433
  user: "postgres"
  password: "postgres"
  dbname: "authly_test"
  sslmode: "disable"

logging:
  level: "info"

