app:
  name: "authly"
  version: "0.2"

server:
  host: "0.0.0.0"
  port: 8000
  domain: "https://auth.test.local"
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
  rate_limit:
    max: 100
    expiration: 60

auth:
  keys_path: "keys"
  active_kid: "main"

database:
  host: "localhost"
  port: 5433
  user: "postgres"
  password: "postgres"
  dbname: "authly_test"
  sslmode: "disable"

logging:
  level: "info"

