app:
  name: "authly"
  version: "0.2"

server:
  host: "0.0.0.0"
  port: 8000
  domain: "https://example.com"
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
  rate_limit:
    max: 100
    expiration: 60

auth:
  keys_path: "keys"
  active_kid: "main"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "authly"
  sslmode: "disable"

logging:
  level: "info"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

